[build-system]
requires = [
  "setuptools",
  "setuptools-scm[toml]",
]
build-backend = "setuptools.build_meta"

[tool.mypy]
warn_unreachable = true
warn_unused_ignores = true
warn_redundant_casts = true
enable_error_code = [
    "ignore-without-code",
    "truthy-bool",
]
